### ISSUE TITLE
Add pre-commit to ensure code quality

### ISSUE THREAD

**Issue by akafael** [akafael/ufpe-project-bsg#18]
Add [pre-commit](https://pre-commit.com/) as tool to enable a local quality gate. This could be used to following verification:

1. Ensure a consistent code format;
2. Ensure all test are passing before the pull request is created;
3. Prevent small issues such missing a proper line break at end of file;

**Comment by SSDaniel** [comment]
We successfully implemented this.

**Comment by akafael** [comment]
There is no PR associated. I am moving it back to open.
