### ISSUE TITLE
Makefile not working on Windows

### ISSUE THREAD

**Issue by pdsfilho** [akafael/ufpe-project-bsg#21]
`make` command error:

```bash
ufpe-project-bsg\code> make
process_begin: CreateProcess(NULL, dirname ufpe-project-bsg/code/Makefile, ...) failed.
Makefile:14: pipe: No error
"Use: make -f Makefile [OPTION] [TARGETS]"
"\nTARGETS"
'sed' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
make: *** [Makefile:30: help] Error 255
```

`make build` command error
```
ufpe-project-bsg\code>make build
process_begin: CreateProcess(NULL, dirname ufpe-project-bsg/code/Makefile, ...) failed.
Makefile:14: pipe: No error
gcc -Wall -c bsg.c
process_begin: CreateProcess(NULL, gcc -Wall -c bsg.c, ...) failed.
make (e=2): O sistema nÒo pode encontrar o arquivo especificado.
make: *** [Makefile:42: bsg.o] Error 2
```

**Comment by SSDaniel** [comment]
Instal the software via Windows Administrator PowerShell, for ensure the local Get-ExecutionPolicy is not set to restricted. Chocolately suggests using Bypass to bypass the policy to get things installed or AllSigned for increased security.

First, you need to run the Get-ExecutionPolicy. If it returns Restricted, then we need to run one of the two commands below.
$ Set-ExecutionPolicy AllSigned
OR
$ Set-ExecutionPolicy Bypass -Scope Process
Now run the following command in the Windows shell.
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) 

them, at the CMD, run:
choco install make
