### ISSUE TITLE
Create function to return the current battery state as ENUM, considering the values for Voltage and Current

### ISSUE THREAD

**Issue by akafael** [akafael/ufpe-project-bsg#27]
* [x] Review Requirements Documentation related with Battery
* [x] Create an ENUM to represent each possible state as a single value:
* [x] Create a function that receive the battery struct and return the ENUM value with the battery state
* [x] Create unit tests for each possible battery state
 
 E.g:
```c
BATTERY_DEAD  // Battery.voltage < Min Battery Voltage
BATTERY_CHARGING  // Battery.voltage > Specs Battery Voltage 
....
```

![image](https://github.com/akafael/ufpe-project-bsg/assets/2273898/013d5e7a-21a1-4188-a357-9d7df5a8ec63)

**Comment by pjmbs** [comment]
is this classification reffering to the 48V battery?
