### ISSUE TITLE
Update Simulink models to reflect current code structure

### ISSUE THREAD

**Issue by akafael** [akafael/ufpe-project-bsg#76]
Create a Simulink sub model for each component?

* [x] #80
* [x] #81
* [x] #82
* [x] #83
* [x] #84

Current code structure:
![image](https://github.com/akafael/ufpe-project-bsg/assets/2273898/720681e3-f9d9-4b4c-b5ae-5106d7fa7a68)

Suggestion: group the following as models;
![image](https://github.com/akafael/ufpe-project-bsg/assets/2273898/e224e8b5-6a4f-4d92-bfbe-7cdc45e8486a)

**Comment by akafael** [comment]
#8

**Comment by pjmbs** [comment]
Model is up to date with code and is functional.
